server:
  port: 8080

spring:
  application:
    name: weather-api-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

rabbitmq:
  queue:
    request: weather.request.queue
    aggregated: weather.aggregated.queue
  exchange:
    weather: weather.exchange
  routing-key:
    request: weather.request
    aggregated: weather.aggregated