server:
  port: 8082

spring:
  application:
    name: weather-aggregator-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

rabbitmq:
  queue:
    request: weather.request.queue
    response: weather.response.queue
    aggregated: weather.aggregated.queue
  exchange:
    weather: weather.exchange
  routing-key:
    request: weather.request
    response: weather.response
    aggregated: weather.aggregated

aggregator:
  timeout: 30 # Таймаут ожидания всех ответов в секундах